### ISSUE TITLE
How to retrieve all available channels information

### ISSUE THREAD

**Issue by HosseinArabbeigi** [c-ong/hikvision-for-droid#3]
Hi

Thanks for amazing example.
In you project channel number is hard coded. how to can i access other channels details dynamic?
I want to show all available cameras in device.

Thanks.

**Comment by c-ong** [comment]
I am truly sorry, it’s long time to Maintenance, And I was leave that  Team.

**Comment by HosseinArabbeigi** [comment]
Thanks @c-ong for response dear.
